### ISSUE TITLE
PAC SWEPs make an 'ammo empty sound' when used

### ISSUE THREAD

**Issue by snepderg** [CFC-Servers/cfc_pac_sweps#7]
A few users have expressed that it annoys them when they click with the PAC SWEPs and it plays a clicking sound.

Simple fix? I don't know, I'll have to keep this in mind when we do a refactor.

**Comment by wrefgtzweve** [comment]
Think i got an easy fix for it, i'll try it real quick

**Comment by snepderg** [comment]
Cool, ty Redox :)
